version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:4173"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules

  dev:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev